// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdi0vcwYiVZqLh9WK8KKE4PNy35I1xy5Q',
    appId: '1:373932852803:android:f7d735d2e8694b38f136f6',
    messagingSenderId: '373932852803',
    projectId: 'chatter-app-34215',
    storageBucket: 'chatter-app-34215.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxipW2idI5sap9xRIy5rAMFjYmm3Mf5bQ',
    appId: '1:373932852803:ios:b323cc1fba7e09b2f136f6',
    messagingSenderId: '373932852803',
    projectId: 'chatter-app-34215',
    storageBucket: 'chatter-app-34215.appspot.com',
    androidClientId: '373932852803-sn19knh0tdqf1v0mfspto1sb47uvoups.apps.googleusercontent.com',
    iosClientId: '373932852803-vfkmmaiubn4lbivvc50c16mdlsvu13dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterApp',
  );
}
